### ISSUE TITLE
Top Secret Message Eyes Only

### ISSUE THREAD

**Issue by thetandav** [Zphtry/TInf2#1]
### The Message

`Ьйчжйху црйфаъ фуиуэрн п црутш. Уинт иучхутшрцд иу тузн цруте н цпемер: «Црут фуъул те цчурё». Ихшзуо иучхутшрцд иу ъуёуче н цпемер: «Црут фуъул те чурцчшг ишёнтш». Чхйчно иучхутшрцд иу лнжуче цруте н цпемер: «Црут фуъул те узхустшг ёуьпш». Ьйчжкхчао иучхутшрцд иу шэйо н цпемер: «Црут фуъул те ёурбэшг пухмнтш». Н фучус утн теьерн цфухнчб сйлиш цуёуо учтуцнчйрбту чузу, пепуж црут. Фхуъулно, шцраэеж нъ цфух н ццухш, цфхуцнр, у ькс никч хйьб. Утн хеццпемерн йсш жцк н фуфхуцнрн йзу хеццшинчб нъ. Н фхуъулно цпемер: «Тнпчу нм жец тй жнийр цруте. Црут цужцйс тй фуъул те цчурё, ту йзу тузн фуъулн те цчурёа. Н ут тй фуъул те ёуьпш, чурбпу йзу лнжуч фуъул те ёуьпш, н ут тй фуъул те пухмнтш — йзу шэн фуъулн, н чеплй ут тй фуъул те ишёнтш, е чурбпу йзу ъуёуч фуъул. Црут цуйинтдйч ж цйёй жцк вчу.`

### The Clues
[clue](https://www.dropbox.com/s/7n32pjqa81mi8jf/image1.jpg?dl=0)
`N = 5`

**Comment by Zphtry** [comment]
![image](https://cloud.githubusercontent.com/assets/12675224/14542326/19c16098-0297-11e6-971a-72328f578072.png)

4times

**Comment by thetandav** [comment]
@Zphtry But have you decoded the original message?

**Comment by Zphtry** [comment]
It was a story about four different wrong views

**Comment by thetandav** [comment]
Fuck damn, I've just only now read your message. For the first look I consider that it's the Vigenère cipher or something more complex. But just now i've realized how to deal with that shit. One question what does it mean "4times"? Tipa each "ok" to each story?

**Comment by Zphtry** [comment]
Four turns of right table will give you new info from left

**Comment by thetandav** [comment]
Okay, I think the issue is going to be closed 😬
